version: '3.9'

services:
  fastapi:
    restart: "no"
    hostname: api
    container_name: api
    build:
      dockerfile: server/Dockerfile
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 85"
    volumes:
      - ./:/AI-Hackaton
    ports:
      - '85:85'

  bot:
    restart: "no"
    build:
      dockerfile: bot/Dockerfile
    command: sh -c "python telegram_bot.py"
    container_name: bot

    env_file:
      - ./.env
    volumes:
      - ./:/TG_bot
    depends_on:
      - fastapi