version: '3.9'

services:
  fastapi:
    restart: "no"
    hostname: api
    container_name: api
    build:
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload"
    volumes:
      - ./:/AI-Hackaton
    ports:
      - '85:85'